/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2018-2025 Agorapulse.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://repo.grails.org/grails/core" }
        maven { url "https://repo.grails.org/grails/libs-milestones-local" }
    }
    dependencies {
        classpath "org.apache.grails:grails-gradle-plugin:$grailsGradlePluginVersion"
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:4.5.1"
        classpath "io.spring.gradle:dependency-management-plugin:1.1.7"
    }
}

version "0.1"
group "heist"

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"war"
apply plugin:"org.apache.grails.grails-web"
apply plugin:"org.apache.grails.grails-gsp"
apply plugin:"com.bertramlabs.asset-pipeline"
apply plugin:"io.spring.dependency-management"

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:$springBootVersion"
        mavenBom "org.apache.grails:grails-bom:$grailsVersion"
    }
    applyMavenExclusions = false
}

repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core" }
    maven { url "https://repo.grails.org/grails/libs-milestones-local" }
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
    all {
        resolutionStrategy.dependencySubstitution {
            substitute module('org.apache.grails:grails-plugin-url-mappings') using module("org.apache.grails:grails-url-mappings:$grailsVersion")
            substitute module('org.apache.grails:grails-core') using module("org.apache.grails:grails-core:$grailsVersion")
            substitute module('org.apache.grails:grails-web-boot') using module("org.apache.grails:grails-web-boot:$grailsVersion")
            substitute module('org.apache.grails:grails-logging') using module("org.apache.grails:grails-logging:$grailsVersion")
        }
    }
}

dependencies {
    developmentOnly "org.springframework.boot:spring-boot-devtools:$springBootVersion"
    console "org.apache.grails:grails-console:$grailsVersion"
    implementation "org.springframework.boot:spring-boot-starter-logging:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-validation:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-autoconfigure:$springBootVersion"
    implementation "org.apache.grails:grails-core:$grailsVersion"
    implementation "org.springframework.boot:spring-boot-starter-actuator:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-tomcat:$springBootVersion"
    implementation "org.apache.grails:grails-web-boot:$grailsVersion"
    implementation "org.apache.grails:grails-logging:$grailsVersion"
    implementation "org.apache.grails:grails-databinding:$grailsVersion"
    implementation "org.apache.grails:grails-i18n:$grailsVersion"
    implementation "org.apache.grails:grails-services:$grailsVersion"
    implementation "org.apache.grails:grails-url-mappings:$grailsVersion"
    implementation "org.apache.grails:grails-interceptors:$grailsVersion"
    implementation "org.apache.grails:grails-async:$grailsVersion"
    implementation "org.apache.grails:grails-scaffolding:$grailsVersion"
    implementation "org.apache.grails:grails-data-hibernate5:$grailsVersion"
    implementation "org.hibernate.orm:hibernate-core:6.6.5.Final"
    implementation "org.apache.grails:grails-events:$grailsVersion"
    implementation "org.apache.grails:grails-gsp:$grailsVersion"
    profile "org.apache.grails.profiles:web:$grailsVersion"
    runtimeOnly "org.glassfish.web:el-impl:2.2.1-b05"
    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.apache.tomcat:tomcat-jdbc"
    runtimeOnly "com.bertramlabs.plugins:asset-pipeline-grails:4.5.1"
    testImplementation "org.apache.grails:grails-gorm-testing-support:$grailsVersion"
    testImplementation "org.mockito:mockito-core"
    testImplementation "org.apache.grails:grails-web-testing-support:$grailsVersion"
    testImplementation "org.apache.grails.plugins:geb:$grailsVersion"
    testImplementation "org.seleniumhq.selenium:selenium-remote-driver:4.28.0"
    testImplementation "org.seleniumhq.selenium:selenium-api:4.28.0"
    testImplementation "org.seleniumhq.selenium:selenium-support:4.28.0"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-chrome-driver:4.28.0"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-firefox-driver:4.28.0"

    testImplementation project(':gru-grails')
}

bootRun {
    ignoreExitValue true
    jvmArgs(
        '-Dspring.output.ansi.enabled=always',
        '-noverify',
        '-XX:TieredStopAtLevel=1',
        '-Xmx1024m')
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

tasks.withType(Test) {
    useJUnitPlatform()
}


assets {
    minifyJs = true
    minifyCss = true
}
